<?php

/**
 * Do not edit this file manually, generated by the Yeoman Phalcon generator
 * Register application modules for the Skeleton project
 */
return [
	'frontend' => [
		'className' => '\Skeleton\Frontend\Module',
		'path' => __DIR__ . '/../modules/frontend/Module.php',
	],

	'backend' => [
		'className' => '\Skeleton\Backend\Module',
		'path' => __DIR__ . '/../modules/backend/Module.php',
	],
];


